### ISSUE TITLE
:export support

### ISSUE THREAD

**Issue by JacobWeinbren** [koluch/esbuild-plugin-sass#31]
Hi - hopefully I am not posting too many issues here. Is there any way to support` :export` used in webpack scss?

The colours would be something like

```css
/* Define all colours */
$white: #FFF;
$black: #000;
$text: #242424;
$inverse: #EEE;

/* Export the palette */
:export {
    white: $white;
    black: $black;
    text: $text;
    inverse: $inverse;
}
```

and then in the JS file
```js
import variables from 'variables.scss';
const {
    white,
    black,
    text,
    inverse
} = variables;
```

If it is not possible in this module due to bulk, is there another way to do this in esbuild without manually copying over variable values?
